### PR TITLE
1

### PR DESCRIPTION
**Pull request by sharanyakamath**
with heapsort and shellsort in c++

### CODE REVIEW

**Comment by manparvesh** [comment]
Hi @sharanyakamath 
I suggest you to keep your commit messages and Pull request messages as descriptive as possible.

**Comment by manparvesh** [comment]
Since you are a first time contributor, I'll give you a little checklist to improve:
- [ ] put source file in src folder according to the existing structure.
- [ ] update pull request message
- [ ] update commit messages in next commits. you can't update previous ones
- [ ] write test cases as written in the test folder

**Comment by sharanyakamath** [comment]
Ok will keep this in mind

**Comment by manparvesh** [comment]
@sharanyakamath  I have added [the contributing guide](https://github.com/stlmp/stlmp/blob/master/.github/CONTRIBUTING.md). Please take a look at it and update your PR.

**Comment by manparvesh** [comment]
@sharanyakamath  I am closing this PR for now. Feel free to open a new one once you update it accordingly.

**Pull request closed without merging**
