### PR TITLE
Fixing changes requested about the binary_search implementation

### PR DESCRIPTION
**Pull request by radicalrafi**
#### Short description of what this resolves:

This fixes the changes requested 
#### Changes proposed in this pull request:

- ...
- ...

**Fixes**: #

---

Before submitting, pleqase check if your submission conforms with the following checklist:
- [x] Add tests for all implementations.
- [x] Descriptive pull request message
- [x] Descriptive commit messages
- [x] write test cases as written in the test folder
- [x] use a formatter to format your code according to the google standards.
- [x] folder names should contain underscores '_' instead of spaces
- [x] please write full and descriptive names for variables
- [x] remove main function from the code and add the tests in the tests folder by creating a new file in a similar structure and similar name as others.
- [x] keep your implementation to C++, and write the code in .hpp files
- [x] tests are written in .cpp files

### CODE REVIEW

**Comment by radicalrafi** [comment]
I suggest using a predefined style guide / formatter settings maybe clang format ?

**Comment by manparvesh** [comment]
@radicalrafi as mentioned in the checklist, I suggest using a formatter with the google style guide.

**Comment by radicalrafi** [comment]
I followed Google C++ style guide .

**Comment by manparvesh** [comment]
@radicalrafi it's fine then :+1: I'll approve this PR in October then.

**Pull request merged**
